export const storeProducts = [
  {
    id: 1,
    title: 'White Potterys',
    img: '/img/vase/white-potterys.png',
    price: 115.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: 'Wine Pottery',
    img: '/img/vase/wine-pottery.png',
    price: 95.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: 'Wine Bowl',
    img: '/img/vase/wine-bowl.png',
    price: 115.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: 'Mint Pottery',
    img: '/img/vase/mint-pottery.png',
    price: 115.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },

  {
    id: 5,
    title: 'Orange Ceramic',
    img: '/img/vase/orange-ceramic.png',
    price: 55.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },

  {
    id: 6,
    title: 'Square Pottery',
    img: '/img/vase/square-pottery.png',
    price: 75.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: 'Black Pottery',
    img: '/img/vase/black-pottery.png',
    price: 155.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: 'Silver Pottery',
    img: '/img/vase/silver-pottery.png',
    price: 100.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: 'Mint Bowl',
    img: '/img/vase/mint-bowl.png',
    price: 115.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: 'Gold & Black Pottery',
    img: '/img/vase/gold-black-pottery.png',
    price: 95.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: 'Red Ceramic',
    img: '/img/vase/red-ceramic.png',
    price: 45.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'vase',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: 'Blue Plate',
    img: '/img/plate/blue-plate.png',
    price: 65.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'plate',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 13,
    title: 'Red Plate',
    img: '/img/plate/red-plate.png',
    price: 115.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'plate',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 14,
    title: 'Decor Plate',
    img: '/img/plate/decor-plate.png',
    price: 65.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'plate',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 15,
    title: 'Orange Plate',
    img: '/img/plate/orange-plate.png',
    price: 115.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'plate',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 16,
    title: 'White Cup',
    img: '/img/cup/white-cup.png',
    price: 55.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'mug',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 17,
    title: 'Gray Cup',
    img: '/img/cup/gray-cup.png',
    price: 65.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'mug',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 18,
    title: 'Set Of Potterys',
    img: '/img/cup/set-of-potterys.png',
    price: 125.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'mug',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 19,
    title: 'Dark Bowl',
    img: '/img/cup/dark-bowl.png',
    price: 115.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'mug',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 20,
    title: 'Torquers Vaze',
    img: '/img/cup/torquers-vaze.png',
    price: 95.0,
    info: "The attractions of ceramics lie partly in its contradictions. It is both difficult and easy, with an element beyond our control. It is both extremely fragile and durable. Like 'Sumi' ink painting, it does not lend itself to erasures and indecision.",
    category: 'mug',
    trackNumber: 234567,
    inCart: false,
    count: 0,
    total: 0,
  },
];
